version: '3'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5433:5433'
    container_name: 'pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker

volumes:
  pg-data: